version: '3'

services:
  redis:
    container_name: redis
    platform: linux/x86_64
    image: redis:4.0
    ports: 
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf

